### ISSUE TITLE
Support for Kedsum-TH weather stations

### ISSUE THREAD

**Issue by s1shed** [flipperdevices/flipperzero-good-faps#103]
### Describe the enhancement you're suggesting.

Add support for Kedsum-TH weather stations. This is supported by rtl_433 (https://github.com/merbanan/rtl_433/blob/master/src/devices/kedsum.c)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```
time      : 2023-12-22 22:44:40
model     : Kedsum-TH    ID        : 158
Channel   : 3            Battery level: 0.000      Flags2    : 0             Temperature: -6.00 C      Humidity  : 89 %          Integrity : CRC
*** Saving signal to file g001_433.92M_250k.cu8 (296332 samples, 655360 bytes)
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```
time      : 2023-12-22 22:44:42
model     : Kedsum-TH    ID        : 26
Channel   : 1            Battery level: 0.000      Flags2    : 0             Temperature: 19.61 C      Humidity  : 33 %          Integrity : CRC
*** Saving signal to file g002_433.92M_250k.cu8 (503792 samples, 1048576 bytes)
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```
time      : 2023-12-22 22:45:09
model     : Kedsum-TH    ID        : 250
Channel   : 2            Battery level: 0.000      Flags2    : 0             Temperature: 20.22 C      Humidity  : 37 %          Integrity : CRC
*** Saving signal to file g003_433.92M_250k.cu8 (299724 samples, 655360 bytes)
```

The file [kedsum-th.zip](https://github.com/flipperdevices/flipperzero-firmware/files/13756701/kedsum-th.zip) contains the .cu8 files. 

I converted these to sub files using EvilPete's `subghz_ook_to_sub.py`.  Only one ([g002_433.92M_250k.zip](https://github.com/flipperdevices/flipperzero-firmware/files/13756710/g002_433.92M_250k.zip)) will be detected by rtl_433 when transmitted with the FlipperZero, so I did not include the others.

Please let me know if I can provide anything else to help get this device supported.

**Comment by Skorpionm** [comment]
Well, at least make normal records, in readRaw format.  positive temperatures so that tens and units of degrees and tenths change.  several records of negative temperatures, at the same time attach to each file what is shown on the receiver display.  , that's at least

**Comment by s1shed** [comment]
Thanks for your response. ☺ 

> Well, at least make normal records, in readRaw format. positive temperatures so that tens and units of degrees and tenths change. several records of negative temperatures, at the same time attach to each file what is shown on the receiver display. , that's at least


ACK. Over the next few days I'll work on getting these sorts of readings.

**Comment by s1shed** [comment]
Hi, sorry for the delay.

Attached is a zip file ([kedsum-weather-th_raw.zip](https://github.com/flipperdevices/flipperzero-good-faps/files/13834659/kedsum-weather-th_raw.zip)) with several RAW signals captured with the Flipper, both positive and negative tempertures and various humidity levels.

All of these captures are with a station transmitting on channel 1 of 3. The files within are named with the following format: `degC(humid%).sub`. 


Please let me know if anything else would be of use for me to provide (and sorry for filing this in the wrong project).

**Comment by skotopes** [comment]
@Skorpionm FYI

**Comment by Skorpionm** [comment]
Chek https://github.com/flipperdevices/flipperzero-good-faps/pull/104
you did not send more than one file with different transmitter IDs (it changes when you take out and insert the batteries), all files are recorded on channel 1, all files have a good battery charge. and it is not clear whether the transmitter has a button for forced data sending, there is no photo either (....
I did what I think is correct, but please check it on different channels, with different IDs and other cases.

**Comment by s1shed** [comment]
> Chek #104 you did not send more than one file with different transmitter IDs (it changes when you take out and insert the batteries), all files are recorded on channel 1, all files have a good battery charge. and it is not clear whether the transmitter has a button for forced data sending, there is no photo either (.... I did what I think is correct, but please check it on different channels, with different IDs and other cases.

Thanks for the quick work! I'm sorry that my submission wasn't as helpful as it could have been. 

My FZ can receive signals from one of the weather stations that is currently close, at least. It's on channel 3.

![fztemp](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/c44289f3-babd-4c9c-93c5-093947357a18)

I'll do some tests with it on different channels and with different IDs and will report my results.

**Comment by s1shed** [comment]
It looks good from my end. :+1:  I removed the batteries a few times and switched the channels. The data received by the FZ matches what's on the display.

![channel1](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/bdfffe86-54d3-4c3e-9041-510c46e1ca74)
![channel2](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/70c4dc0e-bd06-42b5-a06e-ccb77504dda2)

**Comment by s1shed** [comment]
> Chek #104 you did not send more than one file with different transmitter IDs (it changes when you take out and insert the batteries), all files are recorded on channel 1, all files have a good battery charge. and it is not clear whether the transmitter has a button for forced data sending, there is no photo either (.... I did what I think is correct, but please check it on different channels, with different IDs and other cases.

The vendor provides the following photos (among others):

![kuva](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/34a145fd-56e1-48f0-97d2-7e8124b37617)
![kuva](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/06763123-d963-4152-8fcc-393e58af7af8)


The transmitters only have two controls: a button to switch the display from °C to °F and a switch to change the channel.

**Comment by s1shed** [comment]
I'll continue testing but by all indications this looks good so far.

![kuva](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/ebfb1ea2-d78d-46b8-a6fd-07ec23403d80)

**Comment by Skorpionm** [comment]
The only question is, is the battery charge displayed correctly?  everything else seems similar

**Comment by s1shed** [comment]
> The only question is, is the battery charge displayed correctly? everything else seems similar

The units themselves do not show the battery charge, but the values in the Weather Station fap match what `rtl_433` receives. 

![kuva](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/30476db4-ec7c-4b67-b676-509b8d015997)
![kuva](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/fab8edd8-e5cb-4199-96da-5448be937ae0)


![kuva](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/ab32d7c9-4e9f-4e6c-a970-023c68e7eae2)
![kuva](https://github.com/flipperdevices/flipperzero-good-faps/assets/8793762/a5ce44c9-98d1-407a-91aa-1dbf163a5bda)

I think the battery charge values can be considered to be correct.

**Comment by Skorpionm** [comment]
Ok!

**Comment by skotopes** [comment]
@Skorpionm merged, please push update to catalog
