### ISSUE TITLE
Picopass app no longer showing FC: and CN:

### ISSUE THREAD

**Issue by strasharo** [flipperdevices/flipperzero-good-faps#113]
Previously the Picopass app used to show the FC: and CN: for a card like this:

![photo_2023-01-08_16-22-04](https://github.com/flipperdevices/flipperzero-good-faps/assets/3337997/d60df67b-e0c0-4451-9814-543eddf3f7e8)
Now after some recent update it shows it like this:
![photo_2024-01-23_12-32-48](https://github.com/flipperdevices/flipperzero-good-faps/assets/3337997/4b197ec6-9f89-451f-add8-d54f18268e58)
I'm unable to find a way to view the FC and CN anymore, which was a very neat and useful feature.

**Comment by bettse** [comment]
It was removed because the parity bits were not checked and it wasn't known to be correct.  
Use any online wiegand calculator (https://www.ccdesignworks.com/wiegand_calc.htm) to get those values from a 26 bit credential.
