### ISSUE TITLE
Picopass Rename Option

### ISSUE THREAD

**Issue by DarkEnder4583** [flipperdevices/flipperzero-good-faps#12]
### Describe the enhancement you're suggesting.

I would like to request a “rename” option for the Picopass app. Currently, there is no simple way to rename any saved Picopass cards (outside of just manually changing it on a computer).

### Anything else?

(Y’all are great! Thanks for your work!)

**Comment by skotopes** [comment]
@bettse I'll keep it here )

**Comment by bettse** [comment]
Might have to wait until after defcon, but that is a common feature picopass should also have

**Comment by bettse** [comment]
@DarkEnder4583 Do you know how to build a fap off a branch?  If so, can you test https://github.com/flipperdevices/flipperzero-good-faps/pull/25 ?

**Comment by DarkEnder4583** [comment]
Unfortunately, I do not. Sorry!

(As a side note, I've tried a couple times to build a fap, but for some reason can't run ./fbt commands on my shell, even though I've installed Git. If you had any tips or docs you could point me to, I would appreciate it.)

**Comment by skotopes** [comment]
@DarkEnder4583 https://github.com/flipperdevices/flipperzero-ufbt then go into app folder and `ufbt launch`

**Comment by bettse** [comment]
Code merged.  I've got some other Defcon-inspired features before we bump the version, but this will be in the part of it.

**Comment by DarkEnder4583** [comment]
@skotopes Thank you! That's very useful!


And thank you @bettse !
