### ISSUE TITLE
weather station has way weaker RX

### ISSUE THREAD

**Issue by DavidIgor** [flipperdevices/flipperzero-good-faps#147]
Im using latest unleashed and weatherstation app is just not pickng signals unless Im like 1meter away from sensor!
this has been a thing for few months now so several unleashed updates.... 
however I remember app working perfectly - wallk on street would pick up few different sensors from like 20-50 meters.

please let me know how to fix it . 
thanks

**Comment by giddyhup** [comment]
Just to let @DavidIgor know that he is not alone: I am observing the same behavior.

**Comment by skotopes** [comment]
You guys do understand that we don't support 3rd party firmware?

**Comment by giddyhup** [comment]
@skotopes yes, I understand that and appreciate the reply. For the sake of clarity, are you implying that 3rd party firmware breaks the Weather Station app?

**Comment by skotopes** [comment]
@giddyhup no bug reports using 3rd party firmware will be accepted.

**Comment by giddyhup** [comment]
I am using 0.98.3 and Weather Station 1.5. In the regular Sub-GHz scanner app I can hear some sensors' bursts. One of the sensors nearby is recognized by rtl_433 as a Nexus-TH. In the Weather Station app I can see the peak bar moving but it no longer shows any found stations.

**Comment by skotopes** [comment]
Was it working differently in previous official releases?

**Comment by giddyhup** [comment]
Yes, I remember catching at least one or two stations. I am trying all modulations.
This is what is happening around me:
![grafik](https://github.com/flipperdevices/flipperzero-good-faps/assets/4533781/604c6912-87c3-4064-a163-d7d6cb4de1e5)

**Comment by skotopes** [comment]
@giddyhup it doesn't make much sense to compare flipper with SDR.

**Comment by giddyhup** [comment]
I know, I just want to show that there are sensors nearby.

**Comment by skotopes** [comment]
@giddyhup the question is can flipper antenna and transceiver get enough signal to demod and decode payload. 
Have you found if old firmware/app version behaves differently?

**Comment by giddyhup** [comment]
OK. I'll see if I can downgrade and install an earlier app version.
