### ISSUE TITLE
mass_storage: MemManage when starting the gadget without connecting Flipper to USB port

### ISSUE THREAD

**Issue by dogtopus** [flipperdevices/flipperzero-good-faps#20]
The app will crash about 1 second after selecting/creating a disk image when Flipper is not already connected to a USB port.

mass_storage version: 1.1
Firmware: 0.88.0

**Comment by skotopes** [comment]
fixed in latest update, soon will be released in catalog

**Comment by dogtopus** [comment]
@skotopes mass_storage is still at v1.1 on the catalog despite the version bump more than a week ago. Something isn't quite right?

**Comment by skotopes** [comment]
@dogtopus nope, everything is fine, we just were testing everything before release.
