### ISSUE TITLE
[NFC Magic] User dictionary is not being used

### ISSUE THREAD

**Issue by M-wie-Moehre** [flipperdevices/flipperzero-good-faps#209]
I have a Mifare Classic 1K key fob where some sectors require a specific key that is in the user dictionary.
When reading the key fob with the normal nfc app, everything works and all sectors are read.
However when using nfc magic, only the first few sectors (not with the specific key) are read successfully and the all other sectors aren't.
For the sectors, that aren't read immediately, it goes through the system dictionary but apparently can't find the key. The access bits of these sectors are the default (`FF0780`), so they shouldn't be the issue.
Do I have to enable the user dictionary for nfc magic or am I missing something else?

**Comment by M-wie-Moehre** [comment]
I now figured out, that nfc magic really doesn't use the user dictionary. When downloading the system dict and manually adding the specific key (from the user dict) to it, it works fine. The only problem with that is, that the system dict will be overwritten, when upgrading the firmware.

**Comment by Astrrra** [comment]
Can you please provide the full dump of the card you're writing to and the dump you're trying to write to it, as well as your user dictionary? I'm not able to reproduce your issue right now, the user dictionary is used correctly in my testing.

**Comment by M-wie-Moehre** [comment]
Sure, here are the files. Since it's a demostration, I've just put some random numbers in block 8 that I want to write.
[files.zip](https://github.com/flipperdevices/flipperzero-good-faps/files/15298713/files.zip)

**Comment by Astrrra** [comment]
Please check that the issue has been solved and re-open if not
