### ISSUE TITLE
[NFC Magic] Information about shadow mode

### ISSUE THREAD

**Issue by Basobeltza** [flipperdevices/flipperzero-good-faps#210]
Hello,
I can't find information about the shadow mode options.
Specifically the options:

pre-write
restore
disable
disable (high-speed)
split

Could someone briefly explain to me what they consist of?

I clarify that I have a magic card and that it works well with the flipper zero

Thank you so much.

**Comment by skotopes** [comment]
See https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md#set-shadow-mode-gtu
