### ISSUE TITLE
Flipper crashed and was rebooted  furi_check failed

### ISSUE THREAD

**Issue by MBudkin** [flipperdevices/flipperzero-good-faps#238]
Flipper crashed and was rebooted
furi_check failed

NFC Magic gen2

![Screenshot_2024-08-09-00-01-57-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/46d022a0-f45b-435a-89c4-b047d4a47f54)

![Screenshot_2024-08-08-23-59-30-00_965bbf4d18d205f782c6b8409c5773a4](https://github.com/user-attachments/assets/bfc78e9c-4b67-48a4-adf8-f2a6eeae4a88)
![Screenshot_2024-08-08-23-59-48-38_965bbf4d18d205f782c6b8409c5773a4](https://github.com/user-attachments/assets/f3ce2862-0d4f-423e-8114-ff65ebee6bbf)
![Screenshot_2024-08-08-23-59-59-92_965bbf4d18d205f782c6b8409c5773a4](https://github.com/user-attachments/assets/2434b3d1-056a-4bbb-a77b-1e740adf5939)

**Comment by skotopes** [comment]
Please install official firmware and redo tests

**Comment by MBudkin** [comment]
Thanks, reinstallation solved the problem.
