### ISSUE TITLE
[Weather Station] Add function to switch between Celsius and Farenheit

### ISSUE THREAD

**Issue by devmckenzie** [flipperdevices/flipperzero-good-faps#240]
It seems the Weather_Station app can only display the weather in Celsius. Wondering if this can be implemented. Receiving signal from a TX141THBv2.

**Comment by skotopes** [comment]
Yes we do have locale toolkit for that. We'll add it to to-do list.

**Comment by Skorpionm** [comment]
Сhange the setting along the path Settings -> System -> Units Metric to Imperial and the temperature readings will be displayed in Fahrenheit

**Comment by Skorpionm** [comment]
@devmckenzie  did this solution help you? if yes, close the issue

**Comment by devmckenzie** [comment]
Yes it did! Thanks so much!
