### ISSUE TITLE
Add clock alarm to the clock app

### ISSUE THREAD

**Issue by nothingbutlucas** [flipperdevices/flipperzero-good-faps#260]
Hi there!

So, I use a lot the clock app as a nightstand clock and I was wondering if it could be possible to setup an alarm using the buzzer, vibration, led and maybe screen flash to act as an alarm. Obviously it should only work if the app is open, like in the nightstand situation

I think I don't have the skill to do it, so I'm gonna let this issue here...

**Comment by skotopes** [comment]
It is implemented in https://github.com/flipperdevices/flipperzero-firmware/pull/3906
