### ISSUE TITLE
Unable to exit Picopass emulation

### ISSUE THREAD

**Issue by strasharo** [flipperdevices/flipperzero-good-faps#57]
Hello. While the Picopass emulation works fine, for some reason I'm unable to exit it without resetting the device. 

https://github.com/flipperdevices/flipperzero-good-faps/assets/3337997/26e34c58-6133-4520-ad59-f4d17619fc5c

**Comment by bettse** [comment]
Is this still a problem post-NFC refactor?

**Comment by strasharo** [comment]
The issue is still present.

**Comment by strasharo** [comment]
@bettse should I open a new one or this one can be reopened?

**Comment by bettse** [comment]
given this one got closed out, can you open a new one with reproduction steps?

**Comment by strasharo** [comment]
Sure, will do it now.
