### ISSUE TITLE
Nfc Magic don't work correctly with Gen 4

### ISSUE THREAD

**Issue by Mtt0836** [flipperdevices/flipperzero-good-faps#66]
With the new update **i can successfully:**

- authenticate my card (the password is written reversed from proxmark config eg. prox 01020304 in app 04030201)
- select the card to write
- write only UID

**i can't:**

- write ATQA and SAK, the app write 0000 and 00 forever
- wipe the card, it stay in the waiting animation but no wipe
- change the password of the card

I'm using the Gen4 Lab01 card with RogueMaster RM1024-0158-0.93.1-1129e6e release

Thanks for your help

**Comment by skotopes** [comment]
we don't support 3rd party firmwares
