### ISSUE TITLE
loclass function - "Error opening log file"

### ISSUE THREAD

**Issue by mlinton** [flipperdevices/flipperzero-good-faps#77]
after opening the picopass app, and selecting the Loclass function it responds with "error opening log file".

after selecting back and attempting this again, the application stops responding and a reset is required.

FlipperCLI debug:

95888 [D][BrowserWorker] Start
95898 [D][BrowserWorker] Enter folder: /ext/apps items: 9 idx: -1
95900 [D][BrowserWorker] Load offset: 0 cnt: 50
97622 [D][BrowserWorker] Enter folder: /ext/apps/NFC items: 3 idx: -1
97624 [D][BrowserWorker] Load offset: 0 cnt: 50
98735 [D][BrowserWorker] End
98747 [D][DolphinState] icounter 220, butthurt 11
98752 [I][Loader] Loading /ext/apps/NFC/picopass.fap
98905 [I][Elf] Total size of loaded sections: 44031
98911 [I][Loader] Loaded in 159ms
98914 [I][AnimationManager] Unload animation 'L1_Tv_128x47'
103293 [D][DolphinState] icounter 222, butthurt 11
113807 [D][ViewDispatcher] View changed while key press 2000FF10 -> 2000C360. Sending key: Back, type: Release, sequence: 0000004C to previous view port

**Comment by bettse** [comment]
Fixed by https://github.com/flipperdevices/flipperzero-good-faps/pull/78
